### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by ninjaa292** [reneeichhorn/bevy-remote-devtools#1]
When I put  `bevy-remote-devtools-plugin = { git = "https://github.com/reneeichhorn/bevy-remote-devtools.git" }`  into the Cargo.toml of my pre-existing project and tried to compile, I got this long error 

![2021-12-20 20_27_42-Cargo toml - brrrrd - Visual Studio Code](https://user-images.githubusercontent.com/96455623/146860570-229bd64d-0813-43cc-9ed3-a420bb033b31.png)

is there anything I should be doing that I'm not, or something I did wrong?

**Comment by reneeichhorn** [comment]
Are you using bevy 0.5? The plugin targets bevy main branch. I should have mentioned this in the Readme.

**Comment by ninjaa292** [comment]
Trying to use the main branch of bevy also seems to not work for me, though that isn't really a problem with your plugin. I'll try to figure something out then, thanks!
